lsi: false
safe: true
baseurl: ''
theme: minima
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - github-pages-health-check  