lsi: false
safe: true
theme: minima
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - github-pages-health-check
  - "jekyll-github-metadata"
  - 'jekyll-paginate'
  - jekyll-relative-links 